name: Deploy Playground

on:
  push:
    branches:
      - main

  workflow_dispatch:  # Allow manual workflow dispatch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Enable Corepack
       run: corepack enable

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
         node-version: "20"
         cache: npm

     - name: Install Root Dependencies
       run: npm install

     - name: Install Lucide Icons
       run: npm install lucide-vue-next

     - name: Build Module
       run: npm run dev:prepare

     - name: Build Playground
       run: npm run dev:build

    #  - name: Generate Playground
    #    run: npm run dev:generate

     - name: Setup Pages
       uses: actions/configure-pages@v5
       with:
        static_site_generator: nuxt

     - name: List Generated Files
       run: ls -R playground/.output/public

     - name: Upload artifact
       uses: actions/upload-pages-artifact@v3
       with:
         path: playground/.output/public

     - name: Deploy to GitHub Pages
       uses: actions/deploy-pages@v4
